Changed cache over to variables. Only render output when producing report. Minor bug fixes.

diff --git a/updates b/updates
--- a/updates
+++ b/updates
@@ -13,60 +13,74 @@ for lib in libfrmt.sh libwiki.sh libupdates.sh; do
 done
 
 makesection() {
-   cache="$1"
-   title="$2"
+   render="$1"; shift
+   cache="$1"; shift
+   title="$1"; shift
 
    frmt new frmtreport $(wiki type)
    frmtreport h1 "$title"
    frmtreport del
-   shift
    done=0
    num="$#"
    for host in "$@"; do
-      if test -e "$cache/$host/$host"; then
-         test ! -z "$cache/$host/$host" && cat "$cache/$host/$host"
-         cts=( $( ls "$cache/$host/" | grep -v "$host" ) )
-         if test "${#cts[*]}" -gt 0; then
+      if test -f "$cache/$host/$host"; then
+         $render "$cache/$host/$host"
+      fi
+
+      unset cts
+      test -d "$cache/$host/" && cts=( $( ls "$cache/$host/" 2> /dev/null | grep -v "$host" ) )
+
+      if test "${#cts[*]}" -gt 0; then
+         ctreport=$(mktemp)
+         ctcount=0
+         for ct in "${cts[@]}"; do
+            if test ! -z "$cache/$host/$ct"; then 
+               $render "$cache/$host/$ct" >> "$ctreport" && ctcount=$(( ctcount + 1 ))
+            fi
+         done
+         if test "$ctcount" -gt 0; then
+            if test ! -f "$cache/$host/$host" ; then
+               frmt new hostreport $(wiki type)
+               hostreport h2 "$host"
+               hostreport del
+            fi
             frmt new frmtreport $(wiki type)
-            frmtreport foldstart "${#cts[@]} containers"
-            for ct in "${cts[@]}"; do
-               test ! -z "$cache/$host/$ct" && cat "$cache/$host/$ct"
-            done
+            frmtreport foldstart "${ctcount} containers"
+            cat "$ctreport"
             frmtreport foldend
             frmtreport del
          fi
+         rm -f "$ctreport"
       fi
    done
 }
 
-report_upgrade() {
-   local output="$1"
-   local h="$2"
-   local host="$3"
-   local ret="$4"
-   local line
-   local stamp="$(date "+%Y/%m/%d %H:%M:%S")"
+verifycache() {
+   local cache="$1"
+   local host="$2"
+   local ct="$3"
+   local dst
 
-   local state="ok"
-   [[ " ${updates_output[*]} " =~ " Configuration file " ]] && state="CONFIG CHANGE"
-   test "$ret" != "0" && state="FAIL"
-   $output "$h" "$host ($state) ($stamp)"
-   $output foldstart "Output ${#updates_output[*]} lines"
-   for line in "${updates_output[@]}"; do
-      $output pre "$line"
-   done
-   $output foldend
+   test -d "$cache/$host" || mkdir -p "$cache/$host"
+
+   dst="$cache/$host/$host"
+   test "$ct" != "" && dst="$cache/$host/$ct"
+   test "$FORCE" -eq 1 && return 0
+   if test -e "$dst"; then
+      lastmod=$(stat -c "%Y" "$dst")
+      test $(( $(date "+%s") - lastmod )) -lt $MAXCACHEAGE && return 1
+   fi
+   return 0
 }
 
-report_check() {
+check-render-host() {
    local output="$1"
    local h="$2"
    local host="$3"
-   local ret="$4"
    local line
-   local stamp="$(date "+%Y/%m/%d %H:%M:%S")"
+   local stamp="$(date -d "@$date" "+%Y/%m/%d %H:%M:%S")"
 
-   $output "$h" "$host"
+   $output "$h" "$host ($stamp)"
    unset p1 p2
    test "${#updates_avail[*]}" -gt 0 && local p1="${#updates_avail[*]} updates"
    test "${#updates_hold[*]}" -gt 0 && local p2="${#updates_hold[*]} hold"
@@ -82,150 +96,23 @@ report_check() {
    $output foldend
 }
 
-checkcache() {
-   local cache="$1"
-   local host="$2"
-   local ct="$3"
-   local dst
+check-report-hosts() {
+   local src="$1"
+   local head="h2"
 
-   test -d "$cache/$host" || mkdir -p "$cache/$host"
+   unset host date ctname ctid updates_avail updates_hold updates_curver updates_newver updates_newversrc
+   . "$src"
 
-   dst="$cache/$host/$host"
-   test "$ct" != "" && dst="$cache/$host/$ct"
-   test "$FORCE" -eq 1 && return 0
-   if test -e "$dst"; then
-      lastmod=$(stat -c "%Y" "$dst")
-      test $(( $(date "+%s") - lastmod )) -lt $MAXCACHEAGE && return 1
-   #else
-   #   return 2
+   test "$reporthold" = "off" -a "${#updates_avail[*]}" -eq 0 && return 1
+
+   frmt new checkrender $(wiki type)
+   if test "$ctname" == ""; then
+      check-render-host checkrender h2 "$host"
+   else
+      check-render-host checkrender h3 "$ctname ($ctid@$host)"
    fi
+   checkrender del
    return 0
-}
-
-checkhosts() {
-   local done=0
-   local num="$#"
-   local updatesfound
-   local cache="$CACHE/updates"
-   local opts
-   declare -a opts
-
-   test "$UPDATE" -eq 1 && opts+=( "-u" )
-
-   for host in "$@"; do
-      checkhost=1
-      done=$(( done + 1 ))
-      [[ " ${hostexcl[@]} " =~ " ${host} " ]] && checkhost=0
-
-      updatesfound=0
-      test "${host//./}" = "$host" && { printf "Skipping host ${host}, does not look like fqdn.\n"; continue; }
-      updates is-container "$host" && { printf "Skipping host ${host}, is a container.\n"; continue; }
-      test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s" "$done" "$num" "$host" >&2
-
-      if test "$checkhost" -eq 1 && checkcache "$cache" "$host"; then
-         rm -f "$cache/$host/$host"
-         updates check "${opts[@]}" "$host" || { printf "\33[2K\rError on $host (%s)\n" "$(updates error)" >&2; continue; }
-         if test "${#updates_avail[*]}" -gt 0 -o ${#updates_hold[*]} -gt 0; then
-            updatesfound=1
-            frmt new frmtreport $(wiki type)
-            frmtreport output -f "$cache/$host/$host"
-            report_check frmtreport h2 "$host" "$ret"
-            frmtreport del
-         fi
-      fi
-
-      test "${ctexcl[0]}" = "all" && continue
-      updates list-containers "$host"
-      test "${#containers[*]}" -eq 0 && continue
-      ctdone=1
-      for ctid in "${!containers[@]}"; do
-         local ctname="${containers[$ctid]}"
-         test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s (ct %d/%d, %s)" "$done" "$num" "$host" "$ctdone" "${#containers[*]}" "$ctname" >&2
-         ctdone=$(( ctdone + 1 ))
-         [[ " ${ctexcl[@]} " =~ " ${ctid} " ]] && continue
-         test "${#ctincl[*]}" -gt 0 && [[ ! " ${ctincl[@]} " =~ " ${ctid} " ]] && continue
-         checkcache "$cache" "$host" "$ctname" || continue
-         rm -f "$cache/$host/$ctname"
-         updates check "${opts[@]}" "$host" "$ctid" || { echo "Error on container $ctname ($(updates error))" >&2; continue; }
-         if test "${#updates_avail[*]}" -gt 0 -o ${#updates_hold[*]} -gt 0; then
-            if test "$updatesfound" -eq 0; then
-               frmt new frmtreport $(wiki type)
-               frmtreport output -f "$cache/$host/$host"
-               frmtreport h2 "$host"
-               frmtreport del
-            fi
-            updatesfound=1
-            frmt new frmtreport $(wiki type)
-            frmtreport output -f "$cache/$host/$ctname"
-            report_check frmtreport h3 "$ctname ($ctid@$host)" "$ret"
-            frmtreport del
-         fi
-      done
-   done
-   test "$QUIET" -eq 0 && printf "\33[2K\r" >&2
-}
-
-
-upgradehosts() {
-   local done=0
-   local num="$#"
-   local checkhost dstfile
-   local cache="$CACHE/upgrades"
-   local opts
-   declare -a opts
-
-   test "$DRYRUN" -eq 1 && opts+=( "-s" )
-   test "$DOWNLOAD" -eq 1 && opts+=( "-d" )
-
-   for host in "$@"; do
-      checkhost=1
-      done=$(( done + 1 ))
-      [[ " ${hostexcl[@]} " =~ " ${host} " ]] && checkhost=0
-      test "${host//./}" = "$host" && { printf "Skipping host ${host}, does not look like fqdn.\n"; continue; }
-      updates is-container "$host" && { printf "Skipping host ${host}, is a container.\n"; continue; }
-      test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s" "$done" "$num" "$host" >&2
-
-      if test "$checkhost" -eq 1 && checkcache "$cache" "$host"; then
-         updates check "$host"
-         dstfile="$cache/$host/$host"
-         if test "${#updates_avail[*]}" -gt 0; then
-            frmt new frmtreport $(wiki type)
-            frmtreport output -f "$dstfile"
-            updates upgrade "${opts[@]}" "$host"
-            ret=$?
-            report_upgrade frmtreport h2 "$host" "$ret"
-            frmtreport del
-         else
-            test -e "$dstfile" && touch "$dstfile"
-         fi
-      fi
-
-      test "${ctexcl[0]}" = "all" && continue
-      updates list-containers "$host"
-      test "${#containers[*]}" -eq 0 && continue
-      ctdone=1
-      for ctid in "${!containers[@]}"; do
-         ctdone=$(( ctdone + 1 ))
-         [[ " ${ctexcl[@]} " =~ " ${ctid} " ]] && continue
-         test "${#ctincl[*]}" -gt 0 && [[ ! " ${ctincl[@]} " =~ " ${ctid} " ]] && continue
-         local ctname="${containers[$ctid]}"
-         test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s (ct %d/%d, %s)" "$done" "$num" "$host" "$ctdone" "${#containers[*]}" "$ctname" >&2
-         checkcache "$cache" "$host" "$ctname" || continue
-         updates check "$host" "$ctid"
-         dstfile="$cache/$host/$ctname"
-         if test "${#updates_avail[*]}" -gt 0; then
-            frmt new frmtreport $(wiki type)
-            frmtreport output -f "$dstfile"
-            updates upgrade "${opts[@]}" "$host" "$ctid"
-            ret=$?
-            report_upgrade frmtreport h3 "$ctname ($ctid@$host)" "$ret"
-            frmtreport del
-         else
-            test -e "$dstfile" && touch "$dstfile"
-         fi
-      done
-   done
-   test "$QUIET" -eq 0 && printf "\33[2K\r" >&2
 }
 
 check-report() {
@@ -239,10 +126,177 @@ check-report() {
       unset systems
       [[ -v hostlists[@] ]] && test "${hostlists[$section]}" != "" && systems=( ${hostlists[$section]} )
       [[ -v hostcmds[@] ]] && test "${hostcmds[$section]}" != "" && systems=( $( bash -c "${hostcmds[$section]}" ) )
-      makesection "$cache" "${hostsectionnames[$section]}" "${systems[@]}" >> "$report"
+      makesection check-report-hosts "$cache" "${hostsectionnames[$section]}" "${systems[@]}" >> "$report"
    done
    wiki save "${main[checkreport]}" - < "$report" || { echo "Unable to save to wiki ($(wiki error))."; exit 1; }
    rm -f "$report"
+}
+
+check-save() {
+   local output="$1"
+   local date=$(date "+%s")
+
+   {
+      declare -p host date | sed 's/ --/ -g/'
+      test "$ctname" != "" && declare -p ctname | sed 's/ --/ -g/'
+      test "$ctid" != "" && declare -p ctid | sed 's/ --/ -g/'
+      declare -p updates_avail updates_hold updates_curver updates_newver updates_newversrc | sed 's/ -[aA]/&g/'
+   } > "$output"
+}
+
+check() {
+   local done=0
+   local num="$#"
+   local updatesfound
+   local cache="$CACHE/updates"
+   local opts
+   declare -a opts
+
+   test "$UPDATE" -eq 1 && opts+=( "-u" )
+
+   for host in "$@"; do
+      unset ctname ctid
+      checkhost=1
+      done=$(( done + 1 ))
+      [[ " ${hostexcl[@]} " =~ " ${host} " ]] && checkhost=0
+
+      updatesfound=0
+      test "${host//./}" = "$host" && { printf "Skipping host ${host}, does not look like fqdn.\n"; continue; }
+      updates is-container "$host" && { printf "Skipping host ${host}, is a container.\n"; continue; }
+      test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s" "$done" "$num" "$host" >&2
+
+      if test "$checkhost" -eq 1 && verifycache "$cache" "$host"; then
+         rm -f "$cache/$host/$host"
+         updates check "${opts[@]}" "$host" || { printf "\33[2K\rError on $host (%s)\n" "$(updates error)" >&2; continue; }
+         if test "${#updates_avail[*]}" -gt 0 -o ${#updates_hold[*]} -gt 0; then
+            updatesfound=1
+            check-save "$cache/$host/$host"
+         fi
+      fi
+
+      test "${ctexcl[0]}" = "all" && continue
+      updates list-containers "$host"
+      test "${#containers[*]}" -eq 0 && continue
+      ctdone=1
+      for ctid in "${!containers[@]}"; do
+         local ctname="${containers[$ctid]}"
+         test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s (ct %d/%d, %s)" "$done" "$num" "$host" "$ctdone" "${#containers[*]}" "$ctname" >&2
+         ctdone=$(( ctdone + 1 ))
+         [[ " ${ctexcl[@]} " =~ " ${ctid} " ]] && continue
+         test "${#ctincl[*]}" -gt 0 && [[ ! " ${ctincl[@]} " =~ " ${ctid} " ]] && continue
+         verifycache "$cache" "$host" "$ctname" || continue
+         rm -f "$cache/$host/$ctname"
+         updates check "${opts[@]}" "$host" "$ctid" || { echo "Error on container $ctname ($(updates error))" >&2; continue; }
+         if test "${#updates_avail[*]}" -gt 0 -o ${#updates_hold[*]} -gt 0; then
+            check-save "$cache/$host/$ctname"
+         fi
+      done
+   done
+   test "$QUIET" -eq 0 && printf "\33[2K\r" >&2
+}
+
+upgradehost-save() {
+   local output="$1"
+   local date=$(date "+%s")
+
+   {
+      declare -p host date ret | sed 's/ --/ -g/'
+      test "$ctname" != "" && declare -p ctname | sed 's/ --/ -g/'
+      test "$ctid" != "" && declare -p ctid | sed 's/ --/ -g/'
+      declare -p updates_output | sed 's/ -[aA]/&g/'
+   } > "$output"
+}
+
+upgrade() {
+   local done=0
+   local num="$#"
+   local checkhost dstfile
+   local cache="$CACHE/upgrades"
+   local opts
+   declare -a opts
+
+   test "$DRYRUN" -eq 1 && opts+=( "-s" )
+   test "$DOWNLOAD" -eq 1 && opts+=( "-d" )
+
+   for host in "$@"; do
+      unset ctname ctid
+      checkhost=1
+      done=$(( done + 1 ))
+      [[ " ${hostexcl[@]} " =~ " ${host} " ]] && checkhost=0
+      test "${host//./}" = "$host" && { printf "Skipping host ${host}, does not look like fqdn.\n"; continue; }
+      updates is-container "$host" && { printf "Skipping host ${host}, is a container.\n"; continue; }
+      test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s" "$done" "$num" "$host" >&2
+
+      if test "$checkhost" -eq 1 && verifycache "$cache" "$host"; then
+         updates check "$host"
+         dstfile="$cache/$host/$host"
+         if test "${#updates_avail[*]}" -gt 0; then
+            updates upgrade "${opts[@]}" "$host"
+            ret=$?
+            upgradehost-save "$dstfile"
+         else
+            test -e "$dstfile" && touch "$dstfile"
+         fi
+      fi
+
+      test "${ctexcl[0]}" = "all" && continue
+      updates list-containers "$host"
+      test "${#containers[*]}" -eq 0 && continue
+      ctdone=1
+      for ctid in "${!containers[@]}"; do
+         ctdone=$(( ctdone + 1 ))
+         [[ " ${ctexcl[@]} " =~ " ${ctid} " ]] && continue
+         test "${#ctincl[*]}" -gt 0 && [[ ! " ${ctincl[@]} " =~ " ${ctid} " ]] && continue
+         local ctname="${containers[$ctid]}"
+         test "$QUIET" -eq 0 && printf "\33[2K\r%d/%d %s (ct %d/%d, %s)" "$done" "$num" "$host" "$ctdone" "${#containers[*]}" "$ctname" >&2
+         verifycache "$cache" "$host" "$ctname" || continue
+         updates check "$host" "$ctid"
+         dstfile="$cache/$host/$ctname"
+         if test "${#updates_avail[*]}" -gt 0; then
+            updates upgrade "${opts[@]}" "$host" "$ctid"
+            ret=$?
+            upgradehost-save "$dstfile"
+         else
+            test -e "$dstfile" && touch "$dstfile"
+         fi
+      done
+   done
+   test "$QUIET" -eq 0 && printf "\33[2K\r" >&2
+}
+
+upgrade-render-host() {
+   local output="$1"
+   local h="$2"
+   local host="$3"
+   local ret="$4"
+   local line
+   local stamp="$(date -d "@$date" "+%Y/%m/%d %H:%M:%S")"
+
+   local state="ok"
+   [[ " ${updates_output[*]} " =~ " Configuration file " ]] && state="CONFIG CHANGE"
+   test "$ret" != "0" && state="FAIL"
+   $output "$h" "$host ($state) ($stamp)"
+   $output foldstart "Output ${#updates_output[*]} lines"
+   for line in "${updates_output[@]}"; do
+      $output pre "$line"
+   done
+   $output foldend
+}
+
+upgrade-report-hosts() {
+   local src="$1"
+   local head="h2"
+
+   unset host date ret ctname ctid updates_output
+   . "$src"
+
+   frmt new upgraderender $(wiki type)
+   if test "$ctname" == ""; then
+      upgrade-render-host upgraderender h2 "$host" "$ret"
+   else
+      upgrade-render-host upgraderender h3 "$ctname ($ctid@$host)" "$ret"
+   fi
+   upgraderender del
 }
 
 upgrade-report() {
@@ -256,7 +310,7 @@ upgrade-report() {
       unset systems
       [[ -v hostlists[@] ]] && test "${hostlists[$section]}" != "" && systems=( ${hostlists[$section]} )
       [[ -v hostcmds[@] ]] && test "${hostcmds[$section]}" != "" && systems=( $( bash -c "${hostcmds[$section]}" ) )
-      makesection "$cache" "${hostsectionnames[$section]}" "${systems[@]}" >> "$report"
+      makesection upgrade-report-hosts "$cache" "${hostsectionnames[$section]}" "${systems[@]}" >> "$report"
    done
    wiki save "${main[upgradereport]}" - < "$report" || { echo "Unable to save to wiki ($(wiki error))."; exit 1; }
    rm -f "$report"
@@ -283,6 +337,7 @@ usage() {
       echo
       echo "Options:"
       echo "   -h            This help."
+      echo "   -H            Exclude packages on hold from report."
       echo "   -p <page>     Name of the page to upload to (defaults to ${main[checkreport]})."
       ;;
    "upgrade") echo "$0 $1 <options> [host fqdn..]"
@@ -385,9 +440,10 @@ arguments() {
       test "${#hosts[*]}" -eq 0 && hosts=( "${allhosts[@]}" )
    ;;
    "check-report")
-      while getopts :hfp:i:e:E: opt; do
+      while getopts :hHfp:i:e:E: opt; do
          case $opt in
          h) usage $action;;
+         H) reporthold=off;;
          p) main[checkreport]="$OPTARG" ;;
          \?) echo "Unknown option: -$OPTARG"; usage $action;;
          :) echo "Option -$OPTARG requires argument"; usage $action;;
@@ -445,13 +501,13 @@ main() {
    wiki profile "${main[wikiprofile]}" || { echo "Unable to open wiki ($(wiki error))"; exit 1; }
    case "$action" in
    "check")
-      checkhosts "${hosts[@]}"
+      check "${hosts[@]}"
    ;;
    "check-report")
       check-report
    ;;
    "upgrade")
-      upgradehosts "${hosts[@]}"
+      upgrade "${hosts[@]}"
    ;;
    "upgrade-report")
       upgrade-report
